# 如果你不知道这是什么，请不要修改这个文件

# 二楼东/二楼西/四楼/三楼大厅/自定义
二楼东:
  begin: 10002
  end: 10469
  type: 自习室
二楼西:
  begin: 60710
  end: 61129
  type: 自习室
四楼:
  begin: 28756
  end: 29231
  type: 自习室
三楼大厅:
  begin: 58841
  end: 58899
  type: 自习室
守正书院:
  begin: 42710
  end: 42842
  type: 生活区
求新书院:
  begin: 42887
  end: 42978
  type: 生活区
自定义:
  begin: 0
  end: 0
  type: 阅览室
