# 如果你不知道这是什么，请不要修改这个文件

# 二楼东/二楼西/四楼/三楼大厅/守正书院/求新书院/自定义
二楼东:
  begin: 42101
  end: 42140
  type: 自习室
二楼西:
  begin: 42141
  end: 42184
  type: 自习室
四楼:
  begin: 43285
  end: 43455
  type: 自习室
三楼大厅:
  begin: 42587
  end: 42700
  type: 自习室
守正书院:
  begin: 42710
  end: 42842
  type: 生活区
求新书院:
  begin: 42887
  end: 42978
  type: 生活区
自定义:
  begin: 43031
  end: 43114
  type: 阅览室
